
import java.io.File;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xp
 */
public class Interfaz extends javax.swing.JFrame {
    File archivo;
    sax gesSax = new sax();
    xpath gesXpath = new xpath();
    dom gesDom = new dom();
    jaxb gesJaxb = new jaxb();

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoPrincipal = new javax.swing.JTextArea();
        AbrirArchivo = new javax.swing.JButton();
        MostrarArchivo = new javax.swing.JButton();
        TusConsultas = new javax.swing.JButton();
        ListaConsultas = new javax.swing.JLabel();
        consultaTodo = new javax.swing.JButton();
        consultaPiloto = new javax.swing.JButton();
        ConsultaEdad = new javax.swing.JButton();
        ConsultaEscuderia = new javax.swing.JButton();
        pilocoConsultar = new javax.swing.JTextField();
        edadConsultar = new javax.swing.JTextField();
        escuderiaCOnsultar = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Nacionalidad = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        Titulos = new javax.swing.JLabel();
        Carreras = new javax.swing.JLabel();
        PuntosCarnet = new javax.swing.JLabel();
        Escuderia = new javax.swing.JLabel();
        Coche = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        TextoConsulta = new javax.swing.JTextField();
        TextoNombre = new javax.swing.JTextField();
        TextoNacionalidad = new javax.swing.JTextField();
        TextoEdad = new javax.swing.JTextField();
        TextoTitulos = new javax.swing.JTextField();
        TextoCarreras = new javax.swing.JTextField();
        TextoCarnet = new javax.swing.JTextField();
        TextoEscuderia = new javax.swing.JTextField();
        TextoCoche = new javax.swing.JTextField();
        TextoNumero = new javax.swing.JTextField();
        AñadirNuevo = new javax.swing.JButton();
        GuardarNuevo = new javax.swing.JButton();
        Nombre2 = new javax.swing.JLabel();
        Nacionalidad2 = new javax.swing.JLabel();
        Edad2 = new javax.swing.JLabel();
        Carreras2 = new javax.swing.JLabel();
        Titulos2 = new javax.swing.JLabel();
        Carnet2 = new javax.swing.JLabel();
        Escuderia2 = new javax.swing.JLabel();
        coche2 = new javax.swing.JLabel();
        numero2 = new javax.swing.JLabel();
        NombreBuscado = new javax.swing.JTextField();
        NacionalidadBuscado = new javax.swing.JTextField();
        EdadBuscado = new javax.swing.JTextField();
        TitulosBuscado = new javax.swing.JTextField();
        CarrerasBuscado = new javax.swing.JTextField();
        CarnetBuscado = new javax.swing.JTextField();
        EscuderiaBuscada = new javax.swing.JTextField();
        CocheBuscado = new javax.swing.JTextField();
        NumeroBuscado = new javax.swing.JTextField();
        NumeroQueBuscar = new javax.swing.JTextField();
        BuscarNumero = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextoPrincipal.setColumns(20);
        TextoPrincipal.setRows(5);
        jScrollPane1.setViewportView(TextoPrincipal);

        AbrirArchivo.setText("Abrir");
        AbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbrirArchivoMouseClicked(evt);
            }
        });

        MostrarArchivo.setText("Mostrar");
        MostrarArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MostrarArchivoMouseClicked(evt);
            }
        });

        TusConsultas.setText("Consultar");
        TusConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TusConsultasMouseClicked(evt);
            }
        });

        ListaConsultas.setText("Consultas :");

        consultaTodo.setText("Todo");
        consultaTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaTodoMouseClicked(evt);
            }
        });

        consultaPiloto.setText("Piloto");
        consultaPiloto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaPilotoMouseClicked(evt);
            }
        });

        ConsultaEdad.setText("Mayores de:");
        ConsultaEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaEdadMouseClicked(evt);
            }
        });

        ConsultaEscuderia.setText("Pilotos por escuderia");
        ConsultaEscuderia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaEscuderiaMouseClicked(evt);
            }
        });

        pilocoConsultar.setText("Nombre piloto:");

        edadConsultar.setText("Edad:");

        escuderiaCOnsultar.setText("Escuderia:");

        Nombre.setText("Nombre:");

        Nacionalidad.setText("Nacionalidad:");

        Edad.setText("Edad:");

        Titulos.setText("Titulos");

        Carreras.setText("Carreras");

        PuntosCarnet.setText("PuntosCarnet");

        Escuderia.setText("Escuderia");

        Coche.setText("Coche");

        Numero.setText("Numero");

        TextoConsulta.setText("Consultas");

        AñadirNuevo.setText("Añadir");
        AñadirNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirNuevoMouseClicked(evt);
            }
        });

        GuardarNuevo.setText("Guardar");
        GuardarNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarNuevoMouseClicked(evt);
            }
        });

        Nombre2.setText("Nombre:");

        Nacionalidad2.setText("Nacionalidad:");

        Edad2.setText("Edad:");

        Carreras2.setText("Carreras");

        Titulos2.setText("Titulos");

        Carnet2.setText("PuntosCarnet");

        Escuderia2.setText("Escuderia");

        coche2.setText("Coche");

        numero2.setText("Numero");

        NumeroQueBuscar.setText("Numero");

        BuscarNumero.setText("Buscar");
        BuscarNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarNumeroMouseClicked(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AbrirArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MostrarArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TextoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addComponent(TusConsultas)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nacionalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Titulos2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carreras2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Carnet2)
                                    .addComponent(Escuderia2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coche2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TitulosBuscado)
                                        .addComponent(CarrerasBuscado)
                                        .addComponent(CarnetBuscado)
                                        .addComponent(NombreBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(NacionalidadBuscado)
                                        .addComponent(EdadBuscado)
                                        .addComponent(EscuderiaBuscada))
                                    .addComponent(NumeroBuscado)
                                    .addComponent(CocheBuscado))))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListaConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(edadConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ConsultaEscuderia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consultaPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ConsultaEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PuntosCarnet)
                                                .addComponent(Escuderia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Coche, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(pilocoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(escuderiaCOnsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                .addComponent(TextoNombre)
                                                .addComponent(TextoNacionalidad)
                                                .addComponent(TextoEdad)
                                                .addComponent(TextoTitulos)
                                                .addComponent(TextoCarreras)
                                                .addComponent(TextoCarnet)
                                                .addComponent(TextoEscuderia)
                                                .addComponent(TextoCoche)
                                                .addComponent(TextoNumero))))))
                            .addComponent(consultaTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(NumeroQueBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BuscarNumero)
                .addGap(18, 18, 18)
                .addComponent(Modificar)
                .addGap(114, 114, 114)
                .addComponent(AñadirNuevo)
                .addGap(40, 40, 40)
                .addComponent(GuardarNuevo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AbrirArchivo)
                            .addComponent(MostrarArchivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(ListaConsultas)
                        .addGap(18, 18, 18)
                        .addComponent(consultaTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consultaPiloto)
                            .addComponent(pilocoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsultaEdad)
                            .addComponent(edadConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConsultaEscuderia)
                            .addComponent(escuderiaCOnsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TusConsultas)
                            .addComponent(TextoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nacionalidad)
                            .addComponent(TextoNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titulos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoTitulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Carreras, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PuntosCarnet)
                            .addComponent(TextoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Escuderia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoEscuderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nacionalidad2)
                            .addComponent(NacionalidadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Edad2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EdadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Titulos2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TitulosBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Carreras2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarrerasBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Carnet2)
                            .addComponent(CarnetBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Escuderia2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscuderiaBuscada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coche2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CocheBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Coche, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumeroBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Numero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AñadirNuevo)
                        .addComponent(GuardarNuevo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NumeroQueBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BuscarNumero)))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbrirArchivoMouseClicked
      JFileChooser fileChooser = new JFileChooser();        
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home"))); 
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
        archivo = fileChooser.getSelectedFile();
        }
    }//GEN-LAST:event_AbrirArchivoMouseClicked

    
    private File guardar(){
        try{
            JFileChooser fileChooser = new JFileChooser();
            File ruta=null;
            fileChooser.setMultiSelectionEnabled(false);
            fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
            int guardar = fileChooser.showSaveDialog(this);
            if(guardar == JFileChooser.APPROVE_OPTION)
                ruta = fileChooser.getSelectedFile();
                gesJaxb.guardar_XML_JAXB(ruta);
               
        }
        catch (Exception ex){
            System.out.println("No se puede acceder al fichero");
        }
        return archivo;
    }
    
    
    
    
    
    
    private void MostrarArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MostrarArchivoMouseClicked
       gesSax.abrir_XML_SAX(archivo);
        TextoPrincipal.setText(gesSax.recorrerSAX());
    }//GEN-LAST:event_MostrarArchivoMouseClicked

    private void consultaTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaTodoMouseClicked
        gesXpath.consulta(archivo, "/pilotos/piloto");
        TextoPrincipal.setText(gesXpath.salida);
    }//GEN-LAST:event_consultaTodoMouseClicked

    private void consultaPilotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaPilotoMouseClicked
       gesXpath.consulta(archivo, "/pilotos/piloto"+"[./nombre="+"'"+pilocoConsultar.getText()+"'"+"]");
       TextoPrincipal.setText(gesXpath.salida);
    }//GEN-LAST:event_consultaPilotoMouseClicked

    private void ConsultaEdadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaEdadMouseClicked
       gesXpath.consulta(archivo, "/pilotos/piloto"+"[./edad>"+edadConsultar.getText() +"]");
       TextoPrincipal.setText(gesXpath.salida);
    }//GEN-LAST:event_ConsultaEdadMouseClicked
///pilotos/piloto[./@escuderia='Ferrari']
    private void ConsultaEscuderiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaEscuderiaMouseClicked
        gesXpath.consulta(archivo, "/pilotos/piloto"+"[./@escuderia="+"'"+escuderiaCOnsultar.getText()+"'"+"]");
       TextoPrincipal.setText(gesXpath.salida);
    }//GEN-LAST:event_ConsultaEscuderiaMouseClicked

    private void TusConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TusConsultasMouseClicked

        gesXpath.consulta(archivo, TextoConsulta.getText());
        TextoPrincipal.setText(gesXpath.salida);

    }//GEN-LAST:event_TusConsultasMouseClicked

    private void AñadirNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirNuevoMouseClicked
        gesDom.abrir_XML_DOM(archivo);
        gesDom.annadirDOM(archivo,TextoNombre.getText(), TextoNacionalidad.getText(), TextoEdad.getText(), TextoTitulos.getText(), TextoCarreras.getText(), TextoCarnet.getText(), TextoEscuderia.getText(), TextoCoche.getText(), TextoNumero.getText());
        
        
    }//GEN-LAST:event_AñadirNuevoMouseClicked

    private void GuardarNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarNuevoMouseClicked
        guardar();
    }//GEN-LAST:event_GuardarNuevoMouseClicked

    private void BuscarNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarNumeroMouseClicked
      gesJaxb.abrir_XML_JAXB(archivo);
        gesJaxb.recorrerJAXByMostrar();
        String buscar = NumeroQueBuscar.getText();
        for(int i = 0; i<gesJaxb.pilotos.size(); i++){
            if(gesJaxb.pilotos.get(i).getNumero().equals(buscar)){
                NombreBuscado.setText(gesJaxb.pilotos.get(i).getNombre());
                NacionalidadBuscado.setText(gesJaxb.pilotos.get(i).getNacionalidad());
                EdadBuscado.setText(gesJaxb.pilotos.get(i).getEdad());
                TitulosBuscado.setText(gesJaxb.pilotos.get(i).getTitulos());
                CarrerasBuscado.setText(gesJaxb.pilotos.get(i).getCarreras());
                CarnetBuscado.setText(gesJaxb.pilotos.get(i).getPuntosCarnet());
                EscuderiaBuscada.setText(gesJaxb.pilotos.get(i).getEscuderia());
                CocheBuscado.setText(gesJaxb.pilotos.get(i).getCoche());
                NumeroBuscado.setText(gesJaxb.pilotos.get(i).getNumero());
                
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_BuscarNumeroMouseClicked

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
         String buscar = NumeroQueBuscar.getText();
        for(int i = 0; i<gesJaxb.pilotos.size(); i++){
            if(gesJaxb.pilotos.get(i).getNumero().equals(buscar)){
                gesJaxb.pilotos.get(i).setNombre(NombreBuscado.getText());
                gesJaxb.pilotos.get(i).setNacionalidad(NacionalidadBuscado.getText());
                gesJaxb.pilotos.get(i).setEdad(EdadBuscado.getText());
                gesJaxb.pilotos.get(i).setTitulos(TitulosBuscado.getText());
                gesJaxb.pilotos.get(i).setCarreras(CarrerasBuscado.getText());
                gesJaxb.pilotos.get(i).setPuntosCarnet(CarnetBuscado.getText());
                gesJaxb.pilotos.get(i).setEscuderia(EscuderiaBuscada.getText());
                gesJaxb.pilotos.get(i).setCoche(CocheBuscado.getText());
                gesJaxb.pilotos.get(i).setNumero(NumeroBuscado.getText());
       
            }
            
        }
        gesJaxb.guardar_XML_JAXB(archivo);
    }//GEN-LAST:event_ModificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirArchivo;
    private javax.swing.JButton AñadirNuevo;
    private javax.swing.JButton BuscarNumero;
    private javax.swing.JLabel Carnet2;
    private javax.swing.JTextField CarnetBuscado;
    private javax.swing.JLabel Carreras;
    private javax.swing.JLabel Carreras2;
    private javax.swing.JTextField CarrerasBuscado;
    private javax.swing.JLabel Coche;
    private javax.swing.JTextField CocheBuscado;
    private javax.swing.JButton ConsultaEdad;
    private javax.swing.JButton ConsultaEscuderia;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Edad2;
    private javax.swing.JTextField EdadBuscado;
    private javax.swing.JLabel Escuderia;
    private javax.swing.JLabel Escuderia2;
    private javax.swing.JTextField EscuderiaBuscada;
    private javax.swing.JButton GuardarNuevo;
    private javax.swing.JLabel ListaConsultas;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton MostrarArchivo;
    private javax.swing.JLabel Nacionalidad;
    private javax.swing.JLabel Nacionalidad2;
    private javax.swing.JTextField NacionalidadBuscado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JTextField NombreBuscado;
    private javax.swing.JLabel Numero;
    private javax.swing.JTextField NumeroBuscado;
    private javax.swing.JTextField NumeroQueBuscar;
    private javax.swing.JLabel PuntosCarnet;
    private javax.swing.JTextField TextoCarnet;
    private javax.swing.JTextField TextoCarreras;
    private javax.swing.JTextField TextoCoche;
    private javax.swing.JTextField TextoConsulta;
    private javax.swing.JTextField TextoEdad;
    private javax.swing.JTextField TextoEscuderia;
    private javax.swing.JTextField TextoNacionalidad;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoNumero;
    private javax.swing.JTextArea TextoPrincipal;
    private javax.swing.JTextField TextoTitulos;
    private javax.swing.JLabel Titulos;
    private javax.swing.JLabel Titulos2;
    private javax.swing.JTextField TitulosBuscado;
    private javax.swing.JButton TusConsultas;
    private javax.swing.JLabel coche2;
    private javax.swing.JButton consultaPiloto;
    private javax.swing.JButton consultaTodo;
    private javax.swing.JTextField edadConsultar;
    private javax.swing.JTextField escuderiaCOnsultar;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numero2;
    private javax.swing.JTextField pilocoConsultar;
    // End of variables declaration//GEN-END:variables
}
